// Generated from: tests\features\IntegrationTest\campaign_leadsContactsOpportunities.feature
import { test } from "playwright-bdd";

test.describe('Campaign Management in Salesforce and adding Lead, opportunity, Contact', () => {

  test.describe('Create a new marketing campaign with complete details', () => {

    test('Example #1', { tag: ['@campaign_leadContact'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('Open a browser and login to the sales force site', null, { page }); 
      await When('Search for "Campaigns" in app launcher', null, { page }); 
      await Then('Click on "New" button of "Campaigns"', null, { page }); 
      await And('I create a new campaign with following details:', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"Campaign Name"},{"value":"End of Year Campaign 2025"}]},{"cells":[{"value":"Type"},{"value":"Conference"}]},{"cells":[{"value":"Status"},{"value":"Planned"}]},{"cells":[{"value":"Active"},{"value":"true"}]},{"cells":[{"value":"Start Date"},{"value":"11/01/2025"}]},{"cells":[{"value":"Expected Revenue"},{"value":"15/01/2026"}]},{"cells":[{"value":"Budgeted Cost"},{"value":"50000"}]},{"cells":[{"value":"Actual Cost"},{"value":"25000"}]},{"cells":[{"value":"Expected Response"},{"value":"0"}]},{"cells":[{"value":"Description"},{"value":"10"}]}]}}, { page }); 
      await Then('I should see the campaign created successfully', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"Campaign Name"},{"value":"End of Year Campaign 2025"}]}]}}, { page }); 
      await When('I click new opportunities in campaign page', null, { page }); 
      await Then('Add opportunity with following details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"Name"},{"value":"New Business Opp"}]},{"cells":[{"value":"Type"},{"value":"New Customer"}]},{"cells":[{"value":"Stage"},{"value":"Prospecting"}]},{"cells":[{"value":"Amount"},{"value":"50000"}]},{"cells":[{"value":"CloseDate"},{"value":"10/10/2024"}]},{"cells":[{"value":"Private"},{"value":"Yes"}]},{"cells":[{"value":"NextStep"},{"value":"Initial Contact"}]},{"cells":[{"value":"Description"},{"value":"New business opportunity test"}]}]}}, { page }); 
      await When('I click Add Leads in campaign page', null, { page }); 
      await And('Fill all fields of lead with following details:', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"Johnny"}]},{"cells":[{"value":"Last Name"},{"value":"Deep"}]},{"cells":[{"value":"Company"},{"value":"Tech Corp Ltd"}]},{"cells":[{"value":"Email"},{"value":"johnny.smith@techcorp.com"}]},{"cells":[{"value":"Phone"},{"value":"9876543210"}]},{"cells":[{"value":"Lead Status"},{"value":"Open - Not Contacted"}]},{"cells":[{"value":"Industry"},{"value":"Technology"}]}]}}, { page }); 
      await Then('Click on Next then Submit button', null, { page }); 
      await Then('I click Add Contacts in campaign page', null, { page }); 
      await Then('Fill Contacts fields with following details:', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"Salutation"},{"value":"Mr."}]},{"cells":[{"value":"FirstName"},{"value":"Jhonnyy"}]},{"cells":[{"value":"LastName"},{"value":"R.Smith"}]},{"cells":[{"value":"AccountName"},{"value":"Test Account 2"}]},{"cells":[{"value":"Title"},{"value":"Sales Manager"}]},{"cells":[{"value":"Phone"},{"value":"+1234567890"}]},{"cells":[{"value":"HomePhone"},{"value":"+1234567891"}]},{"cells":[{"value":"Mobile"},{"value":"+1987654321"}]},{"cells":[{"value":"OtherPhone"},{"value":"+1234567892"}]},{"cells":[{"value":"Fax"},{"value":"+1234567893"}]},{"cells":[{"value":"Email"},{"value":"john.smith@test.com"}]},{"cells":[{"value":"Assistant"},{"value":"Mary Johnson"}]},{"cells":[{"value":"AssistantPhone"},{"value":"+1234567894"}]},{"cells":[{"value":"Department"},{"value":"Sales"}]},{"cells":[{"value":"LeadSource"},{"value":"Web"}]},{"cells":[{"value":"Birthdate"},{"value":"1985-06-15"}]},{"cells":[{"value":"ReportsTo"},{"value":"Sarah Johnson"}]},{"cells":[{"value":"Languages"},{"value":"English,French"}]},{"cells":[{"value":"Level"},{"value":"Primary"}]},{"cells":[{"value":"MailingStreet"},{"value":"123 Main St"}]},{"cells":[{"value":"MailingCity"},{"value":"New York"}]},{"cells":[{"value":"MailingState"},{"value":"NY"}]},{"cells":[{"value":"MailingZip"},{"value":"10001"}]},{"cells":[{"value":"MailingCountry"},{"value":"USA"}]},{"cells":[{"value":"OtherStreet"},{"value":"456 Work St"}]},{"cells":[{"value":"OtherCity"},{"value":"Brooklyn"}]},{"cells":[{"value":"OtherState"},{"value":"NY"}]},{"cells":[{"value":"OtherZip"},{"value":"10002"}]},{"cells":[{"value":"OtherCountry"},{"value":"USA"}]},{"cells":[{"value":"Description"},{"value":"Primary sales contact"}]}]}}, { page }); 
      await Then('Click on Next then Submit button', null, { page }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\features\\IntegrationTest\\campaign_leadsContactsOpportunities.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":8,"pickleLine":82,"tags":["@campaign_leadContact"],"steps":[{"pwStepLine":9,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Open a browser and login to the sales force site","stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Search for \"Campaigns\" in app launcher","stepMatchArguments":[{"group":{"start":11,"value":"\"Campaigns\"","children":[{"start":12,"value":"Campaigns","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":11,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then Click on \"New\" button of \"Campaigns\"","stepMatchArguments":[{"group":{"start":9,"value":"\"New\"","children":[{"start":10,"value":"New","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":25,"value":"\"Campaigns\"","children":[{"start":26,"value":"Campaigns","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"And I create a new campaign with following details:","stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"Then I should see the campaign created successfully","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When I click new opportunities in campaign page","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then Add opportunity with following details","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When I click Add Leads in campaign page","stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":35,"keywordType":"Action","textWithKeyword":"And Fill all fields of lead with following details:","stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then Click on Next then Submit button","stepMatchArguments":[]},{"pwStepLine":19,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then I click Add Contacts in campaign page","stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then Fill Contacts fields with following details:","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":78,"keywordType":"Outcome","textWithKeyword":"Then Click on Next then Submit button","stepMatchArguments":[]}]},
]; // bdd-data-end