// Generated from: tests\features\IntegrationTest\workorders_serviceAppointment.feature
import { test } from "playwright-bdd";

test.describe('Salesforce Work Orders Management', () => {
  test.describe.configure({"mode":"serial"});

  test.describe('Create and Manage New Work Orders with Comprehensive Data', () => {

    test('Example #1', { tag: ['@mode:serial', '@workOrders_serviceAppointment'] }, async ({ Given, When, Then, page }) => { 
      await Given('Open a browser and login to the sales force site', null, { page }); 
      await When('Search for "Work Orders" in app launcher', null, { page }); 
      await Then('Click on "New" button of "Work Orders"', null, { page }); 
      await Then('Fill Work Orders fields with following details:', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"Status"},{"value":"Completed"}]},{"cells":[{"value":"Priority"},{"value":"Medium"}]},{"cells":[{"value":"ParentWorkOrder"},{"value":"00000001"}]},{"cells":[{"value":"Contact"},{"value":"John Doe"}]},{"cells":[{"value":"Account"},{"value":"Testing"}]},{"cells":[{"value":"Asset"},{"value":""}]},{"cells":[{"value":"Case"},{"value":"00001026"}]},{"cells":[{"value":"Entitlement"},{"value":""}]},{"cells":[{"value":"ServiceContract"},{"value":""}]},{"cells":[{"value":"Description"},{"value":"HVAC system maintenance required for building"}]},{"cells":[{"value":"Subject"},{"value":"HVAC System Maintenance"}]}]}}, { page }); 
      await Then('Verify work order is created successfully with details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"Account"},{"value":"Testing"}]}]}}, { page }); 
      await Then('Click on New button of Service Appointments in work Orders page', null, { page }); 
      await Then('Fill Service Appointments fields with following details:', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"Description"},{"value":"Regular HVAC system maintenance for office building"}]},{"cells":[{"value":"Contact"},{"value":"John doe"}]},{"cells":[{"value":"ParentRecordType"},{"value":""}]},{"cells":[{"value":"ParentRecord"},{"value":""}]},{"cells":[{"value":"Status"},{"value":"Scheduled"}]},{"cells":[{"value":"Subject"},{"value":"HVAC System Maintenance"}]},{"cells":[{"value":"WorkType"},{"value":"Work Item A"}]},{"cells":[{"value":"AppointmentType"},{"value":""}]},{"cells":[{"value":"Duration"},{"value":"120"}]},{"cells":[{"value":"DurationType"},{"value":"Hours"}]},{"cells":[{"value":"AdditionalInformation"},{"value":"Customer requests morning appointment"}]},{"cells":[{"value":"Comment"},{"value":"Bring standard HVAC tools"}]},{"cells":[{"value":"CancellationReason"},{"value":"xyz"}]},{"cells":[{"value":"EarliestStartPermittedDate"},{"value":"11/12/2025"}]},{"cells":[{"value":"EarliestStartPermittedTime"},{"value":"8:00 am"}]},{"cells":[{"value":"DueDate"},{"value":"11/12/2025"}]},{"cells":[{"value":"DueTime"},{"value":"7:00 pm"}]},{"cells":[{"value":"ArrivalWindowStartDate"},{"value":"11/12/2025"}]},{"cells":[{"value":"ArrivalWindowStartTime"},{"value":"9:00 am"}]},{"cells":[{"value":"ArrivalWindowEndDate"},{"value":"11/12/2025"}]},{"cells":[{"value":"ArrivalWindowEndTime"},{"value":"10:00 pm"}]},{"cells":[{"value":"ScheduledStartDate"},{"value":"11/12/2025"}]},{"cells":[{"value":"ScheduledStartTime"},{"value":"9:30 am"}]},{"cells":[{"value":"ScheduledEndDate"},{"value":"11/12/2025"}]},{"cells":[{"value":"ScheduledEndTime"},{"value":"11:00 pm"}]},{"cells":[{"value":"ActualStartDate"},{"value":"11/12/2025"}]},{"cells":[{"value":"ActualStartTime"},{"value":"11:00 pm"}]},{"cells":[{"value":"ActualEndDate"},{"value":"11/12/2025"}]},{"cells":[{"value":"ActualEndTime"},{"value":"11:00 pm"}]},{"cells":[{"value":"ActualDuration"},{"value":"1"}]},{"cells":[{"value":"Street"},{"value":"123 Main Street"}]},{"cells":[{"value":"City"},{"value":"New York"}]},{"cells":[{"value":"ZipPostalCode"},{"value":"10001"}]},{"cells":[{"value":"StateProvince"},{"value":""}]},{"cells":[{"value":"Country"},{"value":""}]},{"cells":[{"value":"Phone"},{"value":"(555) 123-4567"}]},{"cells":[{"value":"Email"},{"value":"maintenance@acme.com"}]}]}}, { page }); 
      await Then('Verify service appointment is created successfully with details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"Subject"},{"value":"HVAC System Maintenance"}]}]}}, { page }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\features\\IntegrationTest\\workorders_serviceAppointment.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":9,"pickleLine":71,"tags":["@mode:serial","@workOrders_serviceAppointment"],"steps":[{"pwStepLine":10,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given Open a browser and login to the sales force site","stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When Search for \"Work Orders\" in app launcher","stepMatchArguments":[{"group":{"start":11,"value":"\"Work Orders\"","children":[{"start":12,"value":"Work Orders","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Click on \"New\" button of \"Work Orders\"","stepMatchArguments":[{"group":{"start":9,"value":"\"New\"","children":[{"start":10,"value":"New","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":25,"value":"\"Work Orders\"","children":[{"start":26,"value":"Work Orders","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then Fill Work Orders fields with following details:","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":22,"keywordType":"Outcome","textWithKeyword":"Then Verify work order is created successfully with details","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"Then Click on New button of Service Appointments in work Orders page","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":26,"keywordType":"Outcome","textWithKeyword":"Then Fill Service Appointments fields with following details:","stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then Verify service appointment is created successfully with details","stepMatchArguments":[]}]},
]; // bdd-data-end